AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  vanityPhoneNumberGenerator:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 180
      Role: 'arn:aws:iam::002621368817:role/AWSLambdaFullAccess_vanityNumber'
      Environment:
        Variables:
          sns_arn: 'arn:aws:sns:us-east-1:002621368817:vanityNumberErrorTopic'
          sqs_url: 'https://sqs.us-east-1.amazonaws.com/002621368817/vanityNumberQueue'
          TABLE: Numbers
      DeadLetterQueue:
        Type: SQS
        TargetArn: 'arn:aws:sqs:us-east-1:002621368817:vanityNumberQueue'
      Layers:
        - 'arn:aws:lambda:us-east-1:002621368817:layer:nltk_python_layer:1'
