AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  vanityNumberDisplay:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::002621368817:role/service-role/vanityNumberDisplay-role-caqliqb9
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          SNS: 'arn:aws:sns:us-east-1:002621368817:vanityGeneratorError'
          SQS: 'https://sqs.us-east-1.amazonaws.com/002621368817/vanityNumberQueue'
          TABLE: Numbers
